version: '3.7'

volumes:
  grafana_data: {}


networks:
  catnet:
    driver: bridge

services:

  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    container_name: "minio"
    volumes:
      - ./data/minio:/data
    environment:
      # MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_USER: myaccesskey
      MINIO_ROOT_PASSWORD: mysecretkey
    command: server /data
    networks:
      - catnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "--console-address", ":9001", "/data"]

    

  thanos_sidecar:
    image: thanosio/thanos:main-2022-05-25-6a312a74
    container_name: "thanos_sidecar"
    volumes:
      - ./prometheus:/etc/config/
      - ./data/prometheus:/data
    command:
      - 'sidecar'
      - '--tsdb.path=/data'
      - '--log.level=debug'
      - '--prometheus.url=http://prometheus:9090'
      - '--reloader.config-file=/etc/config/prometheus.yml'
      # - "--objstore.config-file=/data/thanos/bucket_storage.yml"
      - |
          --objstore.config=type: S3
          config: 
            bucket: thanos-data-bucket
            access_key: myaccesskey
            secret_key: mysecretkey
            endpoint: minio:9000
            insecure: true
    ports:
      - 10901
      - 10902
    networks:
      - catnet
    depends_on:
      - minio
      - prometheus

  thanos_querier:
    image: thanosio/thanos:main-2022-05-25-6a312a74
    container_name: thanos_querier
    command:
      - "query"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--store=thanos_sidecar:10901"
      - "--store=thanos_store:10901"
      - "--store.sd-interval=5m"
      - "--query.replica-label=monitor"
    expose:
      - 10902
      - 10901
    ports:
      - "10902:10902"
    networks:
      - catnet
    depends_on:
      - thanos_sidecar

  thanos_store:
    image: thanosio/thanos:main-2022-05-25-6a312a74
    container_name: thanos_store
    volumes:
      - ./data/store:/data
    command:
      - "store"
      - "--log.level=debug"
      - |
        --objstore.config=type: S3
        config: 
          bucket: thanos-data-bucket
          access_key: myaccesskey
          secret_key: mysecretkey
          endpoint: minio:9000
          insecure: true

      - "--data-dir=/data"
      - "--log.format=logfmt"
      - "--index-cache-size=250MB"
      - "--chunk-pool-size=1GB"
      - "--store.grpc.series-max-concurrency=20"
      - "--sync-block-duration=3m"
      - "--block-sync-concurrency=20"
    restart: unless-stopped
    expose:
      - 10902
      - 10901
    depends_on:
      - thanos_querier
    ports:
      - '10912:10902'
    networks:
      - catnet

  thanos_compactor:
    image: thanosio/thanos:main-2022-05-25-6a312a74
    container_name: thanos_compactor
    volumes:
      - ./data/compactor:/data
    command:
      - "compact"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - |
        --objstore.config=type: S3
        config: 
          bucket: thanos-data-bucket
          access_key: myaccesskey
          secret_key: mysecretkey
          endpoint: minio:9000
          insecure: true

      - "--data-dir=/data"
      - "--consistency-delay=30m"
      - "--retention.resolution-raw=30d"
      - "--retention.resolution-5m=120d"
      - "--retention.resolution-1h=1y"
      - "--block-sync-concurrency=20"
      - "--compact.concurrency=1"
      - "--delete-delay=15m"
      - "--wait"
      - "--wait-interval=3m"
    expose:
      - 10902
      - 10901
    ports:
      - "10922:10902"
    restart: unless-stopped

    networks:
      - catnet
    depends_on:
      - thanos_store

  thanos_query_frontend:
    image: thanosio/thanos:main-2022-05-25-6a312a74
    container_name: thanos_query_frontend
    command:
      - "query-frontend"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--http-address=0.0.0.0:19090"
      - "--query-frontend.compress-responses"
      - "--query-range.partial-response"
      - "--query-frontend.downstream-url=http://thanos_querier:10902"
      - "--query-range.split-interval=24h"
      - "--query-range.max-retries-per-request=5"
      - "--query-frontend.log-queries-longer-than=5s"
      - "--cache-compression-type=snappy"
    ports:
      - "19090:19090"
    networks:
      - catnet
    depends_on:
      - thanos_querier
    restart: unless-stopped


  
  grafana:
    container_name: "grafana"
    build: ./grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - catnet



  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:v2.35.0
    user: root
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/config/
      - ./data/prometheus:/data

    networks:
      - catnet
    command:
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=2h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.listen-address=:9090'
      - '--storage.tsdb.min-block-duration=5m'
      - '--storage.tsdb.max-block-duration=5m'


  s7driver:
    container_name: "s7driver"
    build: ./s7driver
    restart: always
    ports:
      - 8000
    networks:
      - catnet


